name: Node.js CI

on: push

env:
  NODE_ENV: test

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.18]
        postgres-version: [16.0]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        ports:
          - 5431:5432
        env:
          POSTGRES_PASSWORD: 1234
          POSTGRES_USER: waisy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for formatting
        run: npm run format:check

      - name: Check for linting
        run: npm run lint:check

      - name: GraphQL generate schema
        run: npm run graphql:generate-schema

      - name: Run tests
        run: npm test

      - name: Runt e2e tests
        run: npm run test:e2e
